//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts
    {
        public int ContactId { get; set; }
        public string contactName { get; set; }
        public string contactSurname { get; set; }
        public string contactTelephone { get; set; }
        public string contactEmail { get; set; }
        public int CompanyId { get; set; }
    
        public virtual Companies Companies { get; set; }
    }
}
